server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bidsphere_users
    username: postgres
    password: Rahul@24
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bidsphere111@gmail.com
    password: kdlq qvlo ejhl tnli
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  contact-email:  bidsphere111@gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true